#!bin/sh
#$ -M amanda-moy@uiowa.edu
#$ -N sis2_bwaalign
#$ -cwd
#$ -pe 80cpn 80

module load stack/legacy
module load bwa/0.7.15
module load tophat/2.1.2
module load samtools/1.3.1
module load gatk/4.0.5.2_python-3.6.4

bwa mem -t 24 ~/biol-4386-course-project-amoy-2/sequences/feb_sinistra_reference.fasta ~/reads/sister2/Sister2_lane1_20210213000_S31_L001_1.trim.fastq.gz ~/reads/sister2/Sister2_lane1_20210213000_S31_L001_2.trim.fastq.gz  > ~/biol-4386-course-project-a-moy2/data/A-S2L1.sam
samtools view -hb -F 260 ~/biol-4386-course-project-a-moy2/data/A-S2L1.sam > ~/biol-4386-course-proect-a-moy2/data/A-S2L1.bam
samtools sort -@ 80 ~/biol-4386-course-project-a-moy2/data/A-S2L1.bam -o ~/biol-4386-course-project-a-moy2/data/A-S2L1.sort.bam
bwa mem -t 24 ~/biol-4386-course-project-a-moy2/sequences/feb_sinistra_reference.fasta ~/reads/sister2/Sister2_lane2_20210213000_S63_L002_1.trim.fastq.gz ~/reads/sister2/Sister2_lane2_20210213000_S63_L002_2.trim.fastq.gz  > ~/biol-4386-course-project-a-moy2/data/A-S2L2.sam
samtools view -hb -F 260 ~/biol-4386-course-project-a-moy2/data/A-S2L2.sam > ~/biol-4386-course-project-a-moy2/data/A-S2L2.bam
samtools sort -@ 80 ~/biol-4386-course-project-a-moy2/data/A-S2L2.bam -o ~/biol-4386-course-project-a-moy2/data/A-S2L2.sort.bam
bwa mem -t 24 ~/biol-4386-course-project-a-moy2/seqeunces/feb_sinistra_reference.fasta ~/reads/sister2/Sister2_lane3_20210213000_S95_L003_1.trim.fastq.gz ~/reads/sister2/Sister2_lane3_20210213000_S95_L003_2.trim.fastq.gz  > ~/biol-4386-course-project-a-moy2/data/A-S2L3.sam
samtools view -hb -F 260 ~/biol-4386-course-project-a-moy2/data/A-S2L3.sam > ~/biol-4386-course-project-a-moy2/data/A-S2L3.bam
samtools sort -@ 80 ~/biol-4386-course-project-a-moy2/data/A-S2L3.bam -o ~/biol-4386-course-project-a-moy2/data/A-S2L3.sort.bam
bwa mem -t 24 ~/biol-4386-course-project-a-moy2/sequences/feb_sinistra_reference.fasta ~/reads/sister2/Sister2_lane4_20210213000_S127_L004_2.trim.fastq.gz ~/reads/sister2/Sister2_lane4_20210213000_S127_L004_2.trim.fastq.gz  > ~/biol-4386-course-project-a-moy2/data/A-S2L4.sam
samtools view -hb -F 260 ~/biol-4386-course-project-a-moy2/data/A-S2L4.sam > ~/biol-4386-course-project-a-moy2/data/A-S2L4.bam
samtools sort -@ 80 ~/biol-4386-course-project-a-moy2/data/A-S2L4.bam -o ~/biol-4386-course-project-a-moy2/data/A-S2L4.sort.bam

