#$ -m bea
#!/bin/sh
#$ -m bea
#$ -M amanda-moy@uiowa.edu
#$ -N sis2_bwaalign
#$ -cwd
#$ -pe 56cpn 56

module load stack/legacy
module load bwa/0.7.15
module load tophat/2.1.2
module load samtools/1.3.1
module load gatk/4.0.5.2_python-3.6.4

bwa mem -t 24 ~/unc_sinistra_vc/data/feb_sinistra_reference.fasta ~/reads/sister2/Sister2_lane1_20210213000_S31_L001_1.trim.fastq.gz ~/reads/sister2/Sister2_lane1_20210213000_S31_L001_2.trim.fastq.gz  > ~/unc_sinistra_vc/data/S2L1.sam
samtools view -hb -F 260 ~/unc_sinistra_vc/data/S2L1.sam > ~/unc_sinistra_vc/data/S2L1.bam
samtools sort -@ 80 ~/unc_sinistra_vc/data/S2L1.bam -o ~/unc_sinistra_vc/data/S2L1.sort.bam
bwa mem -t 24 ~/unc_sinistra_vc/data/feb_sinistra_reference.fasta ~/reads/sister2/Sister2_lane2_20210213000_S63_L002_1.trim.fastq.gz ~/reads/sister2/Sister2_lane2_20210213000_S63_L002_2.trim.fastq.gz  > ~/unc_sinistra_vc/data/S2L2.sam
samtools view -hb -F 260 ~/unc_sinistra_vc/data/S2L2.sam > ~/unc_sinistra_vc/data/S2L2.bam
samtools sort -@ 80 ~/unc_sinistra_vc/data/S2L2.bam -o ~/unc_sinistra_vc/data/S2L2.sort.bam
bwa mem -t 24 ~/unc_sinistra_vc/data/feb_sinistra_reference.fasta ~/reads/sister2/Sister2_lane3_20210213000_S95_L003_1.trim.fastq.gz ~/reads/sister2/Sister2_lane3_20210213000_S95_L003_2.trim.fastq.gz  > ~/unc_sinistra_vc/data/S2L3.sam
samtools view -hb -F 260 ~/unc_sinistra_vc/data/S2L3.sam > ~/unc_sinistra_vc/data/S2L3.bam
samtools sort -@ 80 ~/unc_sinistra_vc/data/S2L3.bam -o ~/unc_sinistra_vc/data/S2L3.sort.bam
bwa mem -t 24 ~/unc_sinistra_vc/data/feb_sinistra_reference.fasta ~/reads/sister2/Sister2_lane4_20210213000_S127_L004_2.trim.fastq.gz ~/reads/sister2/Sister2_lane4_20210213000_S127_L004_2.trim.fastq.gz  > ~/unc_sinistra_vc/data/S2L4.sam
samtools view -hb -F 260 ~/unc_sinistra_vc/data/S2L4.sam > ~/unc_sinistra_vc/data/S2L4.bam
samtools sort -@ 80 ~/unc_sinistra_vc/data/S2L4.bam -o ~/unc_sinistra_vc/data/S2L4.sort.bam

